[package]
name = "my-tools"
version = "0.0.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2.0.0-beta", features = [] }

[dependencies]
tauri = { version = "2.0.0-beta", features = ["macos-private-api"] }
tauri-plugin-shell = "2.0.0-beta"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-fs = "2.0.0-beta.10"
tauri-plugin-dialog = "2.0.0-beta.10"
# tauri-plugin-store = "2.0.0-beta.9"
rusqlite = { version = "0.31.0", features = ["bundled"] }
lazy_static = "1.4.0"
tauri-plugin-log = "2.0.0-beta.7"
log = "0.4"
window-vibrancy = "0.5.0"
tantivy = "0.22.0"
tantivy-jieba = "0.11.0"

[target."cfg(target_os = \"macos\")".dependencies]
cocoa = "0.24"
objc = "0.2"

[dependencies.uuid]
version = "1.8.0"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
]
